language: go
go:
- '1.8.1'
sudo: true
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
install:
- glide install
- go get github.com/mjibson/esc
- go get github.com/ahmetb/govvv
- go get github.com/franciscocpg/gox
- go get github.com/tcnksm/ghr
- go get github.com/sanbornm/go-selfupdate
script:
- cd ${TRAVIS_BUILD_DIR}/cmd && go generate && cd ${TRAVIS_BUILD_DIR}
- VERSION=$(cat ./VERSION)
- echo "VERSION = ${VERSION}"
- DIST=${TRAVIS_BUILD_DIR}/dist/rai-docker-volume/stable
- CGO_ENABLED=0 gox -verbose  -os="linux darwin windows" -arch="amd64 386 armv5 armv6
  armv7 arm64" -osarch="!darwin/arm64 linux/ppc64 linux/ppc64le" -ldflags="$(govvv
  -flags) -s -w -extldflags \"-static\"" -output="${DIST}/${VERSION}/{{.OS}}-{{.Arch}}/{{.Dir}}"
  .
before_deploy:
- echo "go-selfupdate generating bindiffs"
- mkdir -p ${DIST}/${VERSION}/binaries
- mkdir -p ${DIST}/latest
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/darwin-386     ${DIST}/${VERSION}/darwin-386/rai-docker-volume        ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/darwin-amd64   ${DIST}/${VERSION}/darwin-amd64/rai-docker-volume      ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-386      ${DIST}/${VERSION}/linux-386/rai-docker-volume         ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-amd64    ${DIST}/${VERSION}/linux-amd64/rai-docker-volume       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-armv5    ${DIST}/${VERSION}/linux-armv5/rai-docker-volume       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-armv6    ${DIST}/${VERSION}/linux-armv6/rai-docker-volume       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-armv7    ${DIST}/${VERSION}/linux-armv7/rai-docker-volume       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-arm64    ${DIST}/${VERSION}/linux-arm64/rai-docker-volume       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-ppc64    ${DIST}/${VERSION}/linux-ppc64/rai-docker-volume       ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/linux-ppc64le  ${DIST}/${VERSION}/linux-ppc64le/rai-docker-volume     ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/windows-386    ${DIST}/${VERSION}/windows-386/rai-docker-volume.exe   ${TRAVIS_BUILD_DIR}/LICENSE.TXT
  ${TRAVIS_BUILD_DIR}/VERSION
- tar --transform 's/.*\///g' -czvf ${DIST}/${VERSION}/binaries/windows-amd64  ${DIST}/${VERSION}/windows-amd64/rai-docker-volume.exe
  ${TRAVIS_BUILD_DIR}/LICENSE.TXT ${TRAVIS_BUILD_DIR}/VERSION
- go-selfupdate -o ${DIST}/updates ${DIST}/${VERSION}/binaries/ ${VERSION}
- cp ${DIST}/${VERSION}/binaries/darwin-386    ${DIST}/latest/darwin-386.tar.gz
- cp ${DIST}/${VERSION}/binaries/darwin-amd64  ${DIST}/latest/darwin-amd64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-386     ${DIST}/latest/linux-386.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-amd64   ${DIST}/latest/linux-amd64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-armv5   ${DIST}/latest/linux-armv5.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-armv6   ${DIST}/latest/linux-armv6.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-armv7   ${DIST}/latest/linux-armv7.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-arm64   ${DIST}/latest/linux-arm64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-ppc64   ${DIST}/latest/linux-ppc64.tar.gz
- cp ${DIST}/${VERSION}/binaries/linux-ppc64le ${DIST}/latest/linux-ppc64le.tar.gz
- cp ${DIST}/${VERSION}/binaries/windows-386   ${DIST}/latest/windows-386.tar.gz
- cp ${DIST}/${VERSION}/binaries/windows-amd64 ${DIST}/latest/windows-amd64.tar.gz
- rm -fr ${DIST}/${VERSION}/binaries
- echo "Copying latest directory to ${DIST}/${TRAVIS_COMMIT}"
- cp -r ${DIST}/latest ${DIST}/${TRAVIS_COMMIT}
deploy:
  provider: s3
  access_key_id: AKIAIAFSJLCCOYB5V3EQ
  secret_access_key:
    secure: M18fULRVeyjlL7yY1KMEUA94qqiDdW+xLAlO7jUkblsU2Ga79ir+k4tj20CYg63BlFwxbnN4oXAR/sR+R+yy3Zk5DmbWifeen8Aqeft3mEELNq63glJSYCxP5hzkhHfpaNVemBgrjAhFrW6INnJHoX+mHfgj9DBGdqmbtxxTHZ4/FZlQUowbnzE5AHUS6Aoh/HWk+ywHh3ef+5Wu7wB2ZB8bWhDApG4MKDxXbfzy7gVKGmPyzf47PlV82FY+NtcDVVAfk5k6S3ehVloxqw3MlJ1XH03FdoH383pOvgBwrxJU2U7j0TFItcx1RUWQCXvHf3aJFSxs3QuFy/MWvVL3DHHMyb2irlaUxo01ABKpvrBF+fC8wcgR8RKezbaAqtbSWx3SRcuw4k0jF/2KmST4aMcXaud5w3c3dtxmXi9Qm1K3RuHV3w90mtlS01qqFcYVMJhnZdihIAJYmLhEOF9MRgJNAnPEUvql/Z1oSM3FFyAcpZjIazZjZsJpxp6QgznkHIMpkcLr9rNFbVTjPaDA93bC/7MeT8LWHrLRWTmoWAH3Q+Zxb+8P/HFixMU6SBfrxBf2R9QGSM5NdwAObCYWzKq69DElfEV//+mQgNIcJl/I8kV2ogevpuHhJX7uJsa1AvkwvlnFPMNueL87qw+sNUc9L5HdXjWB0J+U/06QLpc=
  bucket: files.rai-project.com
  local-dir: dist
  upload-dir: dist
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: rai-project/rai-docker-volume
env:
  global:
    secure: m5Y8hFl56sUL0CW25IQ/dVli4ez9KYrgM5izmKM1XfEhb5sPx/rsVK2ie0dM/UDFS8AgGOxCEOTK1MCBe0bo48sE5aJsftrdziAMkcx5ooZ8VJ0Ut4WPlOa6MddqJQIbMsLVusjstQbtJ1LQrCiX9FyLoA356dipNjVxSKy7uaw7jFHHWjJBLzwn9Kg/bW3L/PbBRpkq66EwKBg2CUtQo/zmVRmuhsju55v8Bl3w6UeaavHlBNqgkM0pimMLfTjOLuJ89q4V/xnbjIZcDlq54rnu5sVkwwOdqA6nCKJeUgxjIvY0Xh2OfuxDadzAJ8nkWfhyEnGLWJCKYjmrUSWDybr/S9C093wlRZ9HLfnC4tcfNy9uOqkke71YhLV3FZiBSqucvWZqv/nFLv97GfmkvQs80abua6t0UcaCasnQxP7c7EirQeTwdqEMU7hH/xWFqda1xsnh1Povtvspzq1pB08WEiu5cg3mdrTzW8kLMrCptjzvH5GeYg3Dcb3hdQhk+Ize8WaSE9ZZAa+V7arqn78MbNnLluPFg01pXEnznWVzEbVOrjly1eqgyycAkkQUIojZ+6Bm9jRXKOOcUBu/PAAyV4judUN+bnpzB+1OzTSc0rnhadVcepvAdkXY5H4j8zhezNbHpEy1mFGS13T8BXizcPqFG0Yu5PqYyU+zjUA=
